import Head from "next/head";
import Card, { Data } from "@/components/Card";
import Layout from "@/components/Layout";
import CardLayout from "@/components/CardLayout";

const data: Data[] = [
  {
    type: "education",
    price: "0",
    features: [
      "50 Payload outputs for AI blocks AI output with watermark",
      "Unlimited flows",
      "GPU model training",
    ],
    isBig: false,
  },
  {
    type: "startup",
    price: "599",
    features: [
      "Unlimited Payload outputs for AI blocks",
      "Unlimited flows",
      "GPU model training",
      "Inference model with maximum 2 stages",
    ],
    isBig: false,
  },
  {
    type: "professional",
    price: "4199",
    features: [
      "Unlimited Payload outputs for AI blocks",
      "Unlimited flows",
      "GPU model training",
      "GPU Inference (Unlimited model)",
      "CPU Inference (Unlimited)",
    ],
    isBig: true,
  },
  {
    type: "enterprises",
    price: "App contact us",
    features: [
      "Unlimited Payload outputs for AI blocks",
      "Unlimited flows",
      "GPU model training",
      "GPU Inference (Unlimited model)",
      "CPU Inference (Unlimited)",
      "Industrial commercial devices plugin",
    ],
    isBig: false,
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex items-center flex-col">
          <p className="text-6xl font-bold text-orange-400 my-10">
            Choose the plan that works for you
          </p>
          <CardLayout>
            {data.map((v, i) => <Card data={v} key={i} />)}
          </CardLayout>
        </div>
      </Layout>
    </>
  );
}
